apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: tanzu-weather-app
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: tanzu-weather-app
spec:
  source:
    git:
      url: https://github.com/PradeepLoganathan/my-weather-project.git
      ref:
        branch: main
